#!/bin/sh

set -e

update_initramfs() {
	echo 'xhci-hcd\n' >> /etc/initramfs-tools/modules
  	if [ -x /usr/sbin/update-initramfs ] && \
	   [ -e /etc/initramfs-tools/initramfs.conf ]; then
  		update-initramfs -u
	fi
}

case "$1" in
	configure)
		update_initramfs
		;;
esac

#DEBHELPER#
