#!/bin/sh

set -e

update_initramfs() {
  	if [ -x "$(which update-initramfs)" ] && \
	   [ -e "/etc/initramfs-tools/initramfs.conf" ]; then
  		update-initramfs -u
	fi
}

case "$1" in
	configure)
		update_initramfs
		;;
esac

#DEBHELPER#
