#!/bin/sh

PREREQ=""

prereqs()
{
echo "$PREREQ"
}

case $1 in
prereqs)
prereqs
exit 0
;;
esac

if [ ! -x /sbin/lvm ]; then
  exit 0
fi

. /usr/share/initramfs-tools/hook-functions

#copy some binaries from thin-provisioning-tools to initramfs
if [ -x /usr/sbin/thin_check ]; then
   copy_exec /usr/sbin/thin_check


  if [ -x /usr/sbin/thin_dump ]; then
     copy_exec /usr/sbin/thin_dump
  fi

  if [ -x /usr/sbin/thin_repair ]; then
     copy_exec /usr/sbin/thin_repair
  fi

  if [ -x /usr/sbin/thin_restore ]; then
     copy_exec /usr/sbin/thin_restore
  fi

  if [ -x /usr/sbin/thin_rmap ]; then
     copy_exec /usr/sbin/thin_rmap
  fi

  if [ -x /usr/sbin/thin_metadata_size ]; then
     copy_exec /usr/sbin/thin_metadata_size
  fi

  manual_add_modules dm_thin_pool
fi
